#!/bin/sh
TOP_DIR=$(cd $(dirname $0);pwd)
DATA_DIR="$TOP_DIR/data"
ICONS_DIR="$TOP_DIR/icons"
IMAGES_DIR="$TOP_DIR/images"

icon=$(cat $DATA_DIR/folderIcons.json | awk -f $TOP_DIR/main.awk -v target="$1")

if [ -z $icon ]; then
    mkdir ./$1
else 
    eval "rsvg-convert -h 120 $ICONS_DIR/$icon.svg > $IMAGES_DIR/$icon.png"
    mkdir ./$1 && fileicon -q set ./$1 $IMAGES_DIR/$icon.png
fi
