#!/bin/sh

TOP_DIR=$(cd $(dirname $0);pwd)
DATA_DIR="$TOP_DIR/data"
ICONS_DIR="$TOP_DIR/icons"
IMAGES_DIR="$TOP_DIR/images"

fileName=$(echo $1 | awk -F . '{print $1}'| tr '[:upper:]' '[:lower:]')
fileExtension=$(echo $1 | awk -F . '{print $2}')

if [ -z "$fileExtension" ]; then
    icon=$(cat $DATA_DIR/fileIcons.json | awk -f $TOP_DIR/main.awk -v target="$fileName")
    if [ -z "$icon" ]; then
        touch ./$1
    else
        rsvg-convert -h 120 $ICONS_DIR/$icon.svg > $IMAGES_DIR/$icon.png
        touch ./$1 && fileicon -q set ./$1 $IMAGES_DIR/$icon.png
    fi
else
    icon=$(cat $DATA_DIR/fileIcons.json | awk -f $TOP_DIR/main.awk -v target="$fileName.$fileExtension")
    if [ -n "$icon" ]; then
        rsvg-convert -h 120 $ICONS_DIR/$icon.svg > $IMAGES_DIR/$icon.png
        touch ./$1 && fileicon -q set ./$1 $IMAGES_DIR/$icon.png
        exit 0
    fi

    icon=$(cat $DATA_DIR/fileIcons.json | awk -f $TOP_DIR/main.awk -v target="$fileExtension")
    if [ -n "$icon" ]; then
        if [ ! -f $IMAGES_DIR/$icon.png ]; then
            rsvg-convert -h 120 $ICONS_DIR/$icon.svg > $IMAGES_DIR/$icon.png
        fi
        touch ./$1 && fileicon -q set ./$1 $IMAGES_DIR/$icon.png
        exit 0
    fi

    touch ./$1
fi
